const example = (jp, kana, vi, parts) => ({ jp, kana, vi, parts });

export const PARTICLE_LESSONS = [
  { id: 'wa', section: 'particles', label: 'は', reading: 'wa', title: 'Chủ đề & đối chiếu',
    intro: 'Đưa một điều ra làm chủ đề: “về X thì…”. は cũng dùng để đối chiếu X với thứ khác.',
    pattern: 'Chủ đề + は + điều muốn nói',
    examples: [
      example('私は学生です。', 'わたしは がくせいです。', 'Tôi là sinh viên.', [['私', 'chủ đề: tôi'], ['は', 'đánh dấu chủ đề'], ['学生です', 'điều nói về tôi']]),
      example('コーヒーは好きです。', 'コーヒーは すきです。', 'Cà phê thì tôi thích.', [['コーヒーは', 'đưa cà phê ra đối chiếu'], ['好きです', 'tôi thích']]),
    ], note: 'は đọc là “wa” khi làm trợ từ. Phủ định không bắt buộc đổi が thành は. コーヒーは好きです có thể gợi đối chiếu với đồ uống khác; sắc thái cụ thể tùy ngữ cảnh.', compare: 'wa-ga' },
  { id: 'ga', section: 'particles', label: 'が', reading: 'ga', title: 'Chủ thể & điều được xác định',
    intro: 'Đánh dấu chủ thể trong mệnh đề; thường xuất hiện khi giới thiệu điều đang có hoặc xác định “ai / cái gì”. Học cả mẫu với 好き, 分かる, ある / いる.',
    pattern: 'X + が + vị ngữ',
    examples: [
      example('私はコーヒーが好きです。', 'わたしは コーヒーが すきです。', 'Tôi thích cà phê.', [['私は', 'chủ đề: tôi'], ['コーヒーが', 'thứ tôi thích'], ['好きです', 'thích']]),
      example('部屋にテレビがありません。', 'へやに テレビが ありません。', 'Trong phòng không có TV.', [['部屋に', 'nơi tồn tại'], ['テレビが', 'thứ đang xét'], ['ありません', 'không có']]),
      example('誰が来ますか。', 'だれが きますか。', 'Ai sẽ đến?', [['誰が', 'hỏi ai là người đến'], ['来ますか', 'sẽ đến?']]),
    ], note: 'が dùng được trong câu khẳng định và phủ định. Với mẫu 好き, đừng thay máy móc bằng を: コーヒーが好きです. が không cần có は đi cùng.', compare: 'wa-ga' },
  { id: 'wo', section: 'particles', label: 'を', reading: 'o', title: 'Đối tượng của hành động',
    intro: 'Ở mức nền tảng, を đánh dấu thứ mà hành động tác động trực tiếp đến: ăn gì, uống gì, đọc gì.',
    pattern: 'Đối tượng + を + động từ',
    examples: [
      example('パンを食べます。', 'パンを たべます。', 'Tôi ăn bánh mì.', [['パン', 'đối tượng: bánh mì'], ['を', 'đánh dấu đối tượng'], ['食べます', 'ăn']]),
      example('本を読みます。', 'ほんを よみます。', 'Tôi đọc sách.', [['本を', 'thứ được đọc'], ['読みます', 'đọc']]),
    ], note: 'を thường đọc là “o”. Không phải mọi từ dịch sang tiếng Việt như một hành động đều dùng を: 日本語が分かります（hiểu tiếng Nhật）. を còn có cách dùng chỉ đường đi / nơi rời khỏi, học sau.' },
  { id: 'ni', section: 'particles', label: 'に', reading: 'ni', title: 'Điểm đến, thời điểm & nơi tồn tại',
    intro: 'に có nhiều vai trò. Ưu tiên ba mẫu: địa điểm tồn tại, điểm đến và thời điểm cụ thể.',
    pattern: 'Nơi + に + ある / いる · Điểm đến + に + 行く · Giờ + に + động từ',
    examples: [
      example('部屋に猫がいます。', 'へやに ねこが います。', 'Trong phòng có mèo.', [['部屋に', 'nơi tồn tại'], ['猫が', 'con vật tồn tại'], ['います', 'có (người / động vật)']]),
      example('学校に行きます。', 'がっこうに いきます。', 'Tôi đi đến trường.', [['学校に', 'điểm đến'], ['行きます', 'đi']]),
      example('七時に起きます。', 'しちじに おきます。', 'Tôi dậy lúc 7 giờ.', [['七時に', 'thời điểm cụ thể'], ['起きます', 'thức dậy']]),
    ], note: '今日・明日・毎日 thường không đi với に khi chỉ thời gian. Với nơi diễn ra hành động như học / ăn, thường dùng で.', compare: 'ni-de' },
  { id: 'de', section: 'particles', label: 'で', reading: 'de', title: 'Nơi hành động & phương tiện',
    intro: 'で đánh dấu nơi diễn ra hành động, hoặc phương tiện / cách thức dùng để làm việc đó.',
    pattern: 'Nơi / phương tiện + で + hành động',
    examples: [
      example('図書館で勉強します。', 'としょかんで べんきょうします。', 'Tôi học ở thư viện.', [['図書館で', 'nơi hành động diễn ra'], ['勉強します', 'học']]),
      example('バスで学校に行きます。', 'バスで がっこうに いきます。', 'Tôi đi xe buýt đến trường.', [['バスで', 'phương tiện'], ['学校に', 'điểm đến'], ['行きます', 'đi']]),
    ], note: 'Trợ từ で sau địa điểm khác với dạng nối của danh từ / tính từ na: 学生で、…（là sinh viên, và…）.', compare: 'ni-de' },
  { id: 'e', section: 'particles', label: 'へ', reading: 'e', title: 'Hướng di chuyển',
    intro: 'へ nhấn hướng di chuyển. Trong nhiều câu với 行く・来る・帰る, cả に và へ đều dùng được.',
    pattern: 'Hướng / nơi đến + へ + động từ di chuyển',
    examples: [
      example('日本へ行きます。', 'にほんへ いきます。', 'Tôi đi Nhật.', [['日本へ', 'hướng / nơi đến'], ['行きます', 'đi']]),
      example('家へ帰ります。', 'いえへ かえります。', 'Tôi về nhà.', [['家へ', 'hướng về nhà'], ['帰ります', 'về']]),
    ], note: 'へ đọc là “e” khi làm trợ từ. Không thay に bằng へ trong mọi trường hợp: 七時に起きます dùng に để chỉ giờ.' },
  { id: 'no', section: 'particles', label: 'の', reading: 'no', title: 'Quan hệ giữa danh từ',
    intro: 'Nối hai danh từ. Danh từ trước mô tả quan hệ với danh từ sau: sở hữu, loại, nội dung, nguồn gốc…',
    pattern: 'Danh từ 1 + の + danh từ 2',
    examples: [
      example('これは私の本です。', 'これは わたしの ほんです。', 'Đây là sách của tôi.', [['これは', 'chủ đề: cái này'], ['私の本', 'sách của tôi'], ['です', 'kết thúc lịch sự']]),
      example('日本語の先生です。', 'にほんごの せんせいです。', 'Là giáo viên tiếng Nhật.', [['日本語の', 'môn / lĩnh vực'], ['先生です', 'giáo viên']]),
    ], note: 'の không phải lúc nào cũng dịch là “của”. 日本語の先生 là giáo viên dạy tiếng Nhật. Tính từ na dùng な trước danh từ; tính từ i giữ い.' },
  { id: 'to', section: 'particles', label: 'と', reading: 'to', title: 'Và, cùng với & nội dung lời nói',
    intro: 'と có nhiều cách dùng: liệt kê danh từ, chỉ người cùng làm, hoặc đánh dấu nội dung nói / tên gọi.',
    pattern: 'A と B · Người + と + hành động · Nội dung + と + 言う',
    examples: [
      example('パンと卵を食べます。', 'パンと たまごを たべます。', 'Tôi ăn bánh mì và trứng.', [['パンと卵', 'liệt kê hai thứ'], ['を', 'đối tượng'], ['食べます', 'ăn']]),
      example('友達と話します。', 'ともだちと はなします。', 'Tôi nói chuyện với bạn.', [['友達と', 'người cùng làm'], ['話します', 'nói chuyện']]),
      example('田中と申します。', 'たなかと もうします。', 'Tôi tên là Tanaka. (trang trọng)', [['田中', 'tên / nội dung'], ['と', 'đánh dấu nội dung gọi tên'], ['申します', 'nói / xưng tên, khiêm nhường']]),
    ], note: 'と trong ～と申します không có nghĩa “và”. 申す là từ khiêm nhường thay cho 言う, không phải một dạng chia của 言う.' },
  { id: 'mo', section: 'particles', label: 'も', reading: 'mo', title: 'Cũng',
    intro: 'Thêm một điều có cùng đặc điểm với điều đã nhắc: “X cũng…”. も thường thay は・が・を trong các mẫu nền tảng.',
    pattern: 'X + も + thông tin chung',
    examples: [
      example('私も学生です。', 'わたしも がくせいです。', 'Tôi cũng là sinh viên.', [['私も', 'tôi cũng vậy'], ['学生です', 'là sinh viên']]),
      example('お茶も飲みます。', 'おちゃも のみます。', 'Tôi cũng uống trà.', [['お茶も', 'thêm trà vào những thứ uống'], ['飲みます', 'uống']]),
    ], note: 'Không ghép はも hoặc をも trong các mẫu này. に・で có thể giữ lại trước も: 学校にも（ở / đến trường nữa）, 家でも（ở nhà cũng）.' },
  { id: 'kara', section: 'particles', label: 'から', reading: 'kara', title: 'Từ… & bởi vì…',
    intro: 'Sau danh từ thời gian / địa điểm, から chỉ điểm bắt đầu. Sau một mệnh đề, から có thể nêu lý do.',
    pattern: 'Giờ / nơi + から · Lý do + から + kết quả',
    examples: [
      example('九時から勉強します。', 'くじから べんきょうします。', 'Tôi học từ 9 giờ.', [['九時から', 'thời điểm bắt đầu'], ['勉強します', 'học']]),
      example('寒いですから、窓を閉めます。', 'さむいですから、まどを しめます。', 'Vì lạnh nên tôi đóng cửa sổ.', [['寒いですから', 'lý do: vì lạnh'], ['窓を', 'đối tượng: cửa sổ'], ['閉めます', 'đóng']]),
    ], note: 'Phân biệt “từ 9 giờ” với “bởi vì lạnh” qua phần đứng trước から. Khi dùng thể thường, danh từ / tính từ na + だから: 休みだから（vì là ngày nghỉ）.' },
  { id: 'made', section: 'particles', label: 'まで', reading: 'made', title: 'Đến…',
    intro: 'まで chỉ giới hạn cuối của thời gian hoặc khoảng di chuyển. Thường gặp cùng から.',
    pattern: 'A + から + B + まで',
    examples: [
      example('九時から五時まで働きます。', 'くじから ごじまで はたらきます。', 'Tôi làm việc từ 9 giờ đến 5 giờ.', [['九時から', 'bắt đầu'], ['五時まで', 'kết thúc'], ['働きます', 'làm việc']]),
      example('駅まで歩きます。', 'えきまで あるきます。', 'Tôi đi bộ đến ga.', [['駅まで', 'giới hạn quãng đường'], ['歩きます', 'đi bộ']]),
    ], note: 'まで = đến mốc đó. までに = trước / chậm nhất vào mốc đó (hạn hoàn thành); đây là cách dùng khác, có thể học sau.' },
  { id: 'ya', section: 'particles', label: 'や', reading: 'ya', title: 'Liệt kê một vài ví dụ',
    intro: 'や nối danh từ để đưa ra vài ví dụ trong một nhóm lớn hơn: “A, B, …”.',
    pattern: 'A + や + B（+ など）',
    examples: [
      example('パンや卵を買います。', 'パンや たまごを かいます。', 'Tôi mua những thứ như bánh mì, trứng…', [['パンや卵', 'một vài thứ trong danh sách'], ['を', 'đối tượng'], ['買います', 'mua']]),
    ], note: 'と liệt kê các mục như một danh sách đầy đủ trong ngữ cảnh; や gợi rằng còn những thứ khác. Không dùng や để nối tùy ý hai động từ.' },
  { id: 'desu', section: 'endings', label: 'です', reading: 'desu', title: 'Kết thúc lịch sự với danh từ / tính từ',
    intro: 'です là dạng kết thúc lịch sự. Sau danh từ / tính từ na, nó tương ứng với だ ở thể thường. Sau tính từ i, thêm です để nói lịch sự.',
    pattern: 'Danh từ / gốc tính từ na / tính từ i + です',
    examples: [
      example('私は学生です。', 'わたしは がくせいです。', 'Tôi là sinh viên.', [['私は', 'chủ đề'], ['学生', 'danh từ'], ['です', 'kết thúc lịch sự']]),
      example('この部屋は静かです。', 'このへやは しずかです。', 'Phòng này yên tĩnh.', [['この部屋は', 'chủ đề'], ['静か', 'gốc tính từ na'], ['です', 'kết thúc lịch sự']]),
      example('おいしいです。', 'おいしいです。', 'Ngon.', [['おいしい', 'tính từ i'], ['です', 'lịch sự']]),
    ], note: 'Không thêm です sau một động từ đã chia ます: 食べます, không dùng 食べますです. Tính từ i quá khứ là おいしかったです; danh từ quá khứ là 学生でした.', compare: 'desu-masu' },
  { id: 'masu', section: 'endings', label: 'ます', reading: 'masu', title: 'Động từ ở thể lịch sự',
    intro: 'ます gắn vào gốc phù hợp của động từ để tạo dạng lịch sự không quá khứ. Không gắn vào danh từ hoặc tính từ.',
    pattern: 'Gốc động từ + ます / ません / ました / ませんでした',
    examples: [
      example('毎日パンを食べます。', 'まいにち パンを たべます。', 'Tôi ăn bánh mì hằng ngày.', [['毎日', 'thói quen'], ['パンを', 'đối tượng'], ['食べます', 'ăn, lịch sự']]),
      example('今日はコーヒーを飲みません。', 'きょうは コーヒーを のみません。', 'Hôm nay tôi không uống cà phê.', [['今日は', 'chủ đề thời gian'], ['コーヒーを', 'đối tượng'], ['飲みません', 'không uống, lịch sự']]),
    ], note: '食べる → 食べます; 飲む → 飲みます. Cách tạo gốc phụ thuộc nhóm động từ; tra bảng trong tab Chia từ.', compare: 'desu-masu' },
  { id: 'ka', section: 'endings', label: 'か', reading: 'ka', title: 'Câu hỏi',
    intro: 'Thêm か sau câu lịch sự để hỏi. Với câu có từ nghi vấn, giữ trợ từ theo vai trò của thành phần đang hỏi.',
    pattern: 'Câu lịch sự + か',
    examples: [
      example('学生ですか。', 'がくせいですか。', 'Bạn là sinh viên à?', [['学生です', 'là sinh viên'], ['か', 'hỏi']]),
      example('何が好きですか。', 'なにが すきですか。', 'Bạn thích gì?', [['何が', 'hỏi thứ được thích'], ['好きです', 'thích'], ['か', 'hỏi']]),
    ], note: 'Không cần đảo trật tự từ như tiếng Anh. Trong hội thoại thân mật, cũng có thể hỏi bằng ngữ điệu; đừng thêm か máy móc vào mọi câu thường.' },
  { id: 'ne', section: 'endings', label: 'ね', reading: 'ne', title: 'Đồng tình & xác nhận',
    intro: 'ね tìm sự chia sẻ hoặc đồng tình: “nhỉ”, “đúng không”. Thường dùng với điều cả hai cùng thấy hoặc có thể cùng biết.',
    pattern: 'Câu + ね',
    examples: [
      example('おいしいですね。', 'おいしいですね。', 'Ngon nhỉ.', [['おいしいです', 'nhận xét: ngon'], ['ね', 'mời đồng tình']]),
      example('今日は寒いですね。', 'きょうは さむいですね。', 'Hôm nay lạnh nhỉ.', [['今日は', 'chủ đề'], ['寒いです', 'lạnh'], ['ね', 'cùng chia sẻ nhận xét']]),
    ], note: 'ね không chỉ để hỏi đúng / sai; nó còn tạo cảm giác cùng chia sẻ. Sắc thái phụ thuộc giọng nói và quan hệ giữa hai người.' },
  { id: 'yo', section: 'endings', label: 'よ', reading: 'yo', title: 'Thông báo & nhấn thông tin',
    intro: 'よ đưa thông tin người nghe có thể chưa biết, hoặc nhấn điều muốn họ chú ý.',
    pattern: 'Câu + よ',
    examples: [
      example('この店は安いですよ。', 'このみせは やすいですよ。', 'Quán này rẻ đấy.', [['この店は', 'chủ đề'], ['安いです', 'thông tin: rẻ'], ['よ', 'báo cho người nghe']]),
      example('バスが来ますよ。', 'バスが きますよ。', 'Xe buýt đến kìa.', [['バスが', 'chủ thể'], ['来ます', 'đến'], ['よ', 'nhắc chú ý']]),
    ], note: 'よ không đơn giản là “lịch sự hơn”. Dùng quá nhiều có thể nghe như đang nhấn mạnh hoặc dạy bảo; ngữ cảnh và giọng nói rất quan trọng.' },
  { id: 'yone', section: 'endings', label: 'よね', reading: 'yo ne', title: 'Xác nhận điều mình nghĩ là đúng',
    intro: 'よね thường dùng khi người nói đã có nhận định và muốn người nghe xác nhận / đồng tình.',
    pattern: 'Câu + よね',
    examples: [
      example('明日は休みですよね。', 'あしたは やすみですよね。', 'Ngày mai là ngày nghỉ, đúng không nhỉ?', [['明日は', 'chủ đề'], ['休みです', 'nhận định'], ['よね', 'mong xác nhận']]),
    ], note: 'So sánh: 休みですか hỏi thông tin; 休みですよね xác nhận điều mình nghĩ là ngày nghỉ. Không phải lúc nào cũng thay thế được nhau.' },
  { id: 'invitation', section: 'endings', label: 'ましょう / ませんか', reading: 'mashou / masen ka', title: 'Rủ rê & đề nghị cùng làm',
    intro: '～ましょう đề nghị “cùng làm…”. ～ませんか thường là lời mời “bạn có muốn cùng… không?”, dù hình thức dùng phủ định.',
    pattern: 'Bỏ ます + ましょう / ませんか',
    examples: [
      example('一緒に食べましょう。', 'いっしょに たべましょう。', 'Cùng ăn nhé.', [['一緒に', 'cùng nhau'], ['食べましょう', 'đề nghị cùng ăn']]),
      example('一緒にお茶を飲みませんか。', 'いっしょに おちゃを のみませんか。', 'Bạn có muốn cùng uống trà không?', [['一緒に', 'cùng nhau'], ['お茶を', 'đối tượng'], ['飲みませんか', 'lời mời']]),
    ], note: '～ませんか có thể là lời mời hoặc câu hỏi phủ định tùy ngữ cảnh. Với 一緒に và hoạt động chung, cách hiểu lời mời rất thường gặp.' },
];

export const COMPARISONS = [
  { id: 'wa-ga', label: 'は ↔ が', title: 'Chủ đề khác với chủ thể / điều được xác định',
    intro: 'Chọn trợ từ theo cách tổ chức thông tin. Khẳng định / phủ định được thể hiện ở vị ngữ, không quyết định phải dùng は hay が.',
    rows: [
      ['Nói về tôi', '私は学生です。', 'わたしは がくせいです。', 'Tôi là sinh viên. は đặt tôi làm chủ đề.'],
      ['Trả lời “ai là sinh viên?”', '私が学生です。', 'わたしが がくせいです。', 'Tôi là người đó. が xác định người thỏa điều đang hỏi.'],
      ['Nói không có TV', 'テレビがありません。', 'テレビが ありません。', 'Không có TV. が vẫn dùng được với phủ định.'],
      ['Đối chiếu giường với thứ khác', 'テレビはあります。でも、ベッドはありません。', 'テレビは あります。でも、ベッドは ありません。', 'TV thì có, nhưng giường thì không. は tạo đối chiếu.'],
    ], note: 'Trong 私はコーヒーが好きです: 私は là chủ đề; コーヒーが là thứ được thích trong mẫu ～が好き. Đừng học quy tắc “は = khẳng định / が = phủ định” hoặc ngược lại.' },
  { id: 'ni-de', label: 'に ↔ で', title: 'Nơi tồn tại khác với nơi diễn ra hành động',
    intro: 'Hỏi: câu đang nói thứ gì tồn tại ở đâu, hay ai làm gì ở đâu?',
    rows: [
      ['Nơi tồn tại', '図書館に本があります。', 'としょかんに ほんが あります。', 'Có sách ở thư viện → nơi + に + ある.'],
      ['Nơi hành động', '図書館で本を読みます。', 'としょかんで ほんを よみます。', 'Đọc sách ở thư viện → nơi + で + hành động.'],
      ['Điểm đến', '図書館に行きます。', 'としょかんに いきます。', 'Đi đến thư viện → điểm đến + に + 行く.'],
    ], note: 'に và で có nhiều cách dùng khác. Đây là cách phân biệt các mẫu địa điểm nền tảng, không phải quy tắc bao trùm mọi câu.' },
  { id: 'desu-masu', label: 'です ↔ ます', title: 'Chọn theo loại vị ngữ',
    intro: 'Cả hai đều tạo cách nói lịch sự, nhưng gắn vào loại từ khác nhau.',
    rows: [
      ['Danh từ', '学生です。', 'がくせいです。', '学生 + です. Không dùng 学生ます.'],
      ['Tính từ na', '静かです。', 'しずかです。', 'Gốc 静か + です. Không dùng 静かなです.'],
      ['Tính từ i', 'おいしいです。', 'おいしいです。', 'Giữ い + です. Quá khứ: おいしかったです.'],
      ['Động từ', '食べます。', 'たべます。', '食べる → 食べ + ます. Không thêm です sau 食べます.'],
    ], note: 'Danh từ không chia đuôi như động từ; だ / です là phần thay đổi. Tab Chia từ cho phép đối chiếu bốn dạng theo thì và phủ định.' },
];
